//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionSet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelectionSet.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critères de Filtrage.
        /// </summary>
        public static string CriteriaFiltersTitle {
            get {
                return ResourceManager.GetString("CriteriaFiltersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant de Sélection.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur &apos;Copier&apos; pour copier&amp;#x0a;les paramètres d&apos;un élément.
        /// </summary>
        public static string HelpTextEmptyFilters {
            get {
                return ResourceManager.GetString("HelpTextEmptyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriété &apos;FromRoom&apos; des portes et fenêtres.
        /// </summary>
        public static string HelpTextFromRoomMethod {
            get {
                return ResourceManager.GetString("HelpTextFromRoomMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour les familles système sans point de calcul (escaliers, garde-corps, etc.).
        /// </summary>
        public static string HelpTextLabelGeometricContactMethod {
            get {
                return ResourceManager.GetString("HelpTextLabelGeometricContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriété &apos;ToRoom&apos; des portes et fenêtres.
        /// </summary>
        public static string HelpTextMethodToRoom {
            get {
                return ResourceManager.GetString("HelpTextMethodToRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour les familles chargeables avec point de calcul.
        /// </summary>
        public static string HelpTextRoomCalculationPointMethod {
            get {
                return ResourceManager.GetString("HelpTextRoomCalculationPointMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Où rechercher les éléments correspondants.
        /// </summary>
        public static string HelpTextSearchField {
            get {
                return ResourceManager.GetString("HelpTextSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de ce plugin.
        /// </summary>
        public static string LabelAboutThisPlugin {
            get {
                return ResourceManager.GetString("LabelAboutThisPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories disponibles :.
        /// </summary>
        public static string LabelAvailideCategories {
            get {
                return ResourceManager.GetString("LabelAvailideCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir Pièces.
        /// </summary>
        public static string LabelChoiceRooms {
            get {
                return ResourceManager.GetString("LabelChoiceRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier les paramètres d&apos;un élément de votre modèle.
        /// </summary>
        public static string LabelCopyParametersFromSampleElement {
            get {
                return ResourceManager.GetString("LabelCopyParametersFromSampleElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout Effacer.
        /// </summary>
        public static string LabelDeleteAll {
            get {
                return ResourceManager.GetString("LabelDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout désélectionner.
        /// </summary>
        public static string LabelDeselectEverything {
            get {
                return ResourceManager.GetString("LabelDeselectEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portes et fenêtres.
        /// </summary>
        public static string LabelDoorsAndWindow {
            get {
                return ResourceManager.GetString("LabelDoorsAndWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout Vider.
        /// </summary>
        public static string LabelEmptyAll {
            get {
                return ResourceManager.GetString("LabelEmptyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string LabelErase {
            get {
                return ResourceManager.GetString("LabelErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer tous les critères.
        /// </summary>
        public static string LabelEraseAllCriteria {
            get {
                return ResourceManager.GetString("LabelEraseAllCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les filtres sélectionnés.
        /// </summary>
        public static string LabelEraseSelectedFilters {
            get {
                return ResourceManager.GetString("LabelEraseSelectedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De la pièce.
        /// </summary>
        public static string LabelFromRoom {
            get {
                return ResourceManager.GetString("LabelFromRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision 3D.
        /// </summary>
        public static string LabelFullCollisionContact {
            get {
                return ResourceManager.GetString("LabelFullCollisionContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact géométrique avec la pièce.
        /// </summary>
        public static string LabelGeometricContactMethod {
            get {
                return ResourceManager.GetString("LabelGeometricContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser.
        /// </summary>
        public static string LabelInvert {
            get {
                return ResourceManager.GetString("LabelInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuelle.
        /// </summary>
        public static string LabelManual {
            get {
                return ResourceManager.GetString("LabelManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner manuellement les éléments en traçant un rectangle.
        /// </summary>
        public static string LabelManualSelection {
            get {
                return ResourceManager.GetString("LabelManualSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthodes de Détection :.
        /// </summary>
        public static string LabelMethodsDetection {
            get {
                return ResourceManager.GetString("LabelMethodsDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun filtre.
        /// </summary>
        public static string LabelNoFilters {
            get {
                return ResourceManager.GetString("LabelNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt à sélectionner.
        /// </summary>
        public static string LabelReadyToSelect {
            get {
                return ResourceManager.GetString("LabelReadyToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les critères doivent correspondre (logique ET).
        /// </summary>
        public static string LabelRemarkCriteria {
            get {
                return ResourceManager.GetString("LabelRemarkCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer.
        /// </summary>
        public static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point de calcul de la pièce.
        /// </summary>
        public static string LabelRoomCalculationPoint {
            get {
                return ResourceManager.GetString("LabelRoomCalculationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étendue de Recherche.
        /// </summary>
        public static string LabelSearchField {
            get {
                return ResourceManager.GetString("LabelSearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout Sélectionner.
        /// </summary>
        public static string LabelSelectEverything {
            get {
                return ResourceManager.GetString("LabelSelectEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner les Pièces :.
        /// </summary>
        public static string LabelSelectRooms {
            get {
                return ResourceManager.GetString("LabelSelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact surface à surface.
        /// </summary>
        public static string LabelSurfacicCollisionContact {
            get {
                return ResourceManager.GetString("LabelSurfacicCollisionContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune catégorie sélectionnée.
        /// </summary>
        public static string ThereIsNoCategorySelectioned {
            get {
                return ResourceManager.GetString("ThereIsNoCategorySelectioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter les éléments filtrés à la sélection actuelle.
        /// </summary>
        public static string TooltipAddToCurrentSelection {
            get {
                return ResourceManager.GetString("TooltipAddToCurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer les éléments filtrés de la sélection actuelle.
        /// </summary>
        public static string ToolTipRemoveSelected {
            get {
                return ResourceManager.GetString("ToolTipRemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remplacer la sélection actuelle par les éléments filtrés.
        /// </summary>
        public static string TooltipReplaceSelection {
            get {
                return ResourceManager.GetString("TooltipReplaceSelection", resourceCulture);
            }
        }
    }
}
